CXXFLAGS = -Wall -g -O3

buildSum: buildTheSum.cpp
	g++ -Wall -O3 -o buildTheSum buildTheSum.cpp 2>&1
shelves: shelves.cpp
	g++ -Wall -O3 -o shelves shelves.cpp 2>&1
faces: faces.cpp
	g++ -Wall -O3 -o faces faces.cpp 2>&1
change: changeDynamic.cpp
	g++ -Wall -O3 -o change changeDynamic.cpp 2>&1

